// Code generated by internal/interposer/cmd/genpmlist; DO NOT EDIT.
//
// Single source of truth: internal/packagemanager/pmlist.InterposerPMs.
// Regenerate via `go generate ./internal/interposer/...` or `make interposer`.

#ifndef VETO_PM_NAMES_H
#define VETO_PM_NAMES_H

static const char *const PM_NAMES[] = {
  "npm",
  "npx",
  "yarn",
  "pnpm",
  "pnpx",
  "rush",
  "rushx",
  "bun",
  "bunx",
  "pip",
  "pip3",
  "uv",
  "uvx",
  "poetry",
  "pipx",
  "pdm",
  "python",
  "python3",
  NULL,
};

#endif // VETO_PM_NAMES_H
