_anchors:
  defaults: &defaults
    inpackage: false
    outpkg: mocks
    filename: "mock_{{.InterfaceName | snakecase}}.go"
    with-expecter: true

packages:
  github.com/brynbellomy/veto/internal/intel:
    config:
      <<: *defaults
      dir: "internal/intel/mocks"
    interfaces:
      Source:
      Store:
  github.com/brynbellomy/veto/internal/packagemanager:
    config:
      <<: *defaults
      dir: "internal/packagemanager/mocks"
    interfaces:
      PackageManager:
