package jslock_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/brynbellomy/veto/internal/intel"
	"github.com/brynbellomy/veto/internal/packagemanager"
	"github.com/brynbellomy/veto/internal/packagemanager/jslock"
)

// TestExpandPackageLockV3 covers the modern (lockfileVersion 3) schema —
// what every npm 9+ user has. Each entry in `packages` keyed by a
// node_modules path becomes one gateable Install.
func TestExpandPackageLockV3(t *testing.T) {
	const lock = `{
		"name": "myapp",
		"lockfileVersion": 3,
		"packages": {
			"": {"name": "myapp", "version": "1.0.0"},
			"node_modules/lodash": {"version": "4.17.21"},
			"node_modules/@types/node": {"version": "20.0.0"},
			"node_modules/express": {"version": "4.18.2"},
			"node_modules/express/node_modules/debug": {"version": "2.6.9"}
		}
	}`
	got := mustExpand(t, "package-lock.json", packagemanager.ManifestKindPackageLockJSON, lock)
	requireContains(t, got, intel.EcosystemNPM, "lodash", "4.17.21")
	requireContains(t, got, intel.EcosystemNPM, "@types/node", "20.0.0")
	requireContains(t, got, intel.EcosystemNPM, "express", "4.18.2")
	// Transitive nested into express's own node_modules.
	requireContains(t, got, intel.EcosystemNPM, "debug", "2.6.9")
	// Root project is NOT gated against itself.
	requireMissing(t, got, "myapp")
}

// TestExpandPackageLockV1 covers the legacy nested-dependencies schema.
// Important because older repos still ship lockfileVersion=1.
func TestExpandPackageLockV1(t *testing.T) {
	const lock = `{
		"name": "myapp",
		"version": "1.0.0",
		"lockfileVersion": 1,
		"dependencies": {
			"lodash": {"version": "4.17.21"},
			"express": {
				"version": "4.18.2",
				"dependencies": {
					"debug": {"version": "2.6.9"}
				}
			}
		}
	}`
	got := mustExpand(t, "package-lock.json", packagemanager.ManifestKindPackageLockJSON, lock)
	requireContains(t, got, intel.EcosystemNPM, "lodash", "4.17.21")
	requireContains(t, got, intel.EcosystemNPM, "express", "4.18.2")
	requireContains(t, got, intel.EcosystemNPM, "debug", "2.6.9")
}

// TestExpandPnpmLockV9 covers the schema-9 packages map.
func TestExpandPnpmLockV9(t *testing.T) {
	const lock = `lockfileVersion: '9.0'
packages:
  /lodash@4.17.21:
    resolution: {integrity: sha512-xxx}
  /@types/node@20.0.0:
    resolution: {integrity: sha512-yyy}
  /react@18.2.0(react-dom@18.2.0):
    resolution: {integrity: sha512-zzz}
`
	got := mustExpand(t, "pnpm-lock.yaml", packagemanager.ManifestKindPnpmLockYAML, lock)
	requireContains(t, got, intel.EcosystemNPM, "lodash", "4.17.21")
	requireContains(t, got, intel.EcosystemNPM, "@types/node", "20.0.0")
	// Peer-suffix is stripped.
	requireContains(t, got, intel.EcosystemNPM, "react", "18.2.0")
}

// TestExpandYarnLockV1 covers the original yarn classic format.
func TestExpandYarnLockV1(t *testing.T) {
	const lock = `# THIS IS AN AUTOGENERATED FILE.

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

"@types/node@^20.0.0":
  version "20.0.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.0.0.tgz"

"express@^4.18.2", "express@~4.18":
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"
`
	got := mustExpand(t, "yarn.lock", packagemanager.ManifestKindYarnLock, lock)
	requireContains(t, got, intel.EcosystemNPM, "lodash", "4.17.21")
	requireContains(t, got, intel.EcosystemNPM, "@types/node", "20.0.0")
	requireContains(t, got, intel.EcosystemNPM, "express", "4.18.2")
}

// TestExpandPnpmLockNpmAlias ensures pnpm packages-map keys of the form
// `/alias@npm:realname@version` resolve to the REAL package, not the alias.
// An attacker landing a package under a clean-looking local name must still
// be gated against the actually-installed name.
func TestExpandPnpmLockNpmAlias(t *testing.T) {
	const lock = `lockfileVersion: '9.0'
packages:
  /lodash@npm:evil@1.0:
    resolution: {integrity: sha512-xxx}
  /react@npm:preact@10.5.0:
    resolution: {integrity: sha512-yyy}
`
	got := mustExpand(t, "pnpm-lock.yaml", packagemanager.ManifestKindPnpmLockYAML, lock)
	requireContains(t, got, intel.EcosystemNPM, "evil", "1.0")
	requireContains(t, got, intel.EcosystemNPM, "preact", "10.5.0")
	// The alias local name must not leak through as a separate Install.
	requireMissing(t, got, "lodash")
	requireMissing(t, got, "react")
}

// TestExpandYarnLockBerryNpmAlias covers yarn-berry headers of the form
// `"alias@npm:realname@version"` — the real package wins over the alias.
func TestExpandYarnLockBerryNpmAlias(t *testing.T) {
	const lock = `# yarn berry lockfile
"lodash@npm:evil@1.0":
  version: 1.0
  resolution: "evil@npm:1.0"
`
	got := mustExpand(t, "yarn.lock", packagemanager.ManifestKindYarnLock, lock)
	requireContains(t, got, intel.EcosystemNPM, "evil", "1.0")
	requireMissing(t, got, "lodash")
}

// TestExpandYarnLock_OversizeLine guards M7: yarn-berry lockfiles for
// large monorepos can legitimately produce header or body lines that
// exceed the old 8 MiB bufio.Scanner cap, which used to truncate silently
// and fail-open. We build a yarn.lock whose header line alone is >8 MiB
// (a long comma-separated list of alternative specs) and confirm the
// parser still recovers the package@version downstream.
//
// Skipped under -short because the input is ~9 MiB; it's not slow to
// generate but there's no reason to pay for it on every CI invocation.
func TestExpandYarnLock_OversizeLine(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping oversize yarn.lock parser test in -short mode")
	}
	// Build a single header line >8 MiB by concatenating many
	// quoted alternative specs separated by ", ". Each alternative is
	// ~64 bytes; we need ~150_000 of them to clear 8 MiB.
	const altsNeeded = 150_000
	var b strings.Builder
	b.Grow(altsNeeded * 80)
	b.WriteString(`"lodash@^4.17.21"`)
	for range altsNeeded {
		b.WriteString(`, "lodash@^4.17.`)
		// Pad the version so each alternative is a substantial chunk
		// of bytes; the exact value is irrelevant — we only check the
		// final pinned `version "..."` below.
		b.WriteString("000000000000000000000000000000000000000000000000")
		b.WriteString(`"`)
	}
	b.WriteString(":\n")
	b.WriteString("  version \"4.17.21\"\n")
	b.WriteString("  resolved \"https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz\"\n")
	lock := b.String()
	if len(lock) < 9*1024*1024 {
		t.Fatalf("test fixture too small: %d bytes (want >9 MiB to exercise the >8 MiB code path)", len(lock))
	}
	got := mustExpand(t, "yarn.lock", packagemanager.ManifestKindYarnLock, lock)
	requireContains(t, got, intel.EcosystemNPM, "lodash", "4.17.21")
}

// TestExpandMissingFile_ReturnsNilNil: PMs emit lock refs speculatively,
// so missing files must not error.
func TestExpandMissingFile_ReturnsNilNil(t *testing.T) {
	exp := jslock.New()
	out, err := exp.Expand(packagemanager.ManifestRef{Path: "/nonexistent/lockfile", Kind: packagemanager.ManifestKindPackageLockJSON})
	require.NoError(t, err)
	require.Nil(t, out)
}

// TestExpandMalformedJSON_Errors: garbage input must fail-closed via
// error, not silently return empty (which would falsely look like
// "lockfile says no transitive deps").
func TestExpandMalformedJSON_Errors(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "package-lock.json")
	require.NoError(t, os.WriteFile(path, []byte("{not json"), 0o644))
	exp := jslock.New()
	_, err := exp.Expand(packagemanager.ManifestRef{Path: path, Kind: packagemanager.ManifestKindPackageLockJSON})
	require.Error(t, err)
	require.Contains(t, err.Error(), "parse package-lock.json")
}

func mustExpand(t *testing.T, name string, kind packagemanager.ManifestKind, contents string) []packagemanager.Install {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, name)
	require.NoError(t, os.WriteFile(path, []byte(contents), 0o644))
	out, err := jslock.New().Expand(packagemanager.ManifestRef{Path: path, Kind: kind})
	require.NoError(t, err)
	return out
}

func requireContains(t *testing.T, installs []packagemanager.Install, eco intel.Ecosystem, name, version string) {
	t.Helper()
	for _, ins := range installs {
		if ins.Ref.Ecosystem == eco && ins.Ref.Name == name && ins.Ref.Version == version {
			return
		}
	}
	t.Fatalf("expected install %s@%s (eco=%s) in:\n%v", name, version, eco, installs)
}

func requireMissing(t *testing.T, installs []packagemanager.Install, name string) {
	t.Helper()
	for _, ins := range installs {
		if ins.Ref.Name == name {
			t.Fatalf("did not expect install named %q in:\n%v", name, installs)
		}
	}
}
