package jslock_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/brynbellomy/veto/internal/intel"
	"github.com/brynbellomy/veto/internal/packagemanager"
	"github.com/brynbellomy/veto/internal/packagemanager/jslock"
)

// TestExpandPackageLockV3 covers the modern (lockfileVersion 3) schema —
// what every npm 9+ user has. Each entry in `packages` keyed by a
// node_modules path becomes one gateable Install.
func TestExpandPackageLockV3(t *testing.T) {
	const lock = `{
		"name": "myapp",
		"lockfileVersion": 3,
		"packages": {
			"": {"name": "myapp", "version": "1.0.0"},
			"node_modules/lodash": {"version": "4.17.21"},
			"node_modules/@types/node": {"version": "20.0.0"},
			"node_modules/express": {"version": "4.18.2"},
			"node_modules/express/node_modules/debug": {"version": "2.6.9"}
		}
	}`
	got := mustExpand(t, "package-lock.json", packagemanager.ManifestKindPackageLockJSON, lock)
	requireContains(t, got, intel.EcosystemNPM, "lodash", "4.17.21")
	requireContains(t, got, intel.EcosystemNPM, "@types/node", "20.0.0")
	requireContains(t, got, intel.EcosystemNPM, "express", "4.18.2")
	// Transitive nested into express's own node_modules.
	requireContains(t, got, intel.EcosystemNPM, "debug", "2.6.9")
	// Root project is NOT gated against itself.
	requireMissing(t, got, "myapp")
}

// TestExpandPackageLockV1 covers the legacy nested-dependencies schema.
// Important because older repos still ship lockfileVersion=1.
func TestExpandPackageLockV1(t *testing.T) {
	const lock = `{
		"name": "myapp",
		"version": "1.0.0",
		"lockfileVersion": 1,
		"dependencies": {
			"lodash": {"version": "4.17.21"},
			"express": {
				"version": "4.18.2",
				"dependencies": {
					"debug": {"version": "2.6.9"}
				}
			}
		}
	}`
	got := mustExpand(t, "package-lock.json", packagemanager.ManifestKindPackageLockJSON, lock)
	requireContains(t, got, intel.EcosystemNPM, "lodash", "4.17.21")
	requireContains(t, got, intel.EcosystemNPM, "express", "4.18.2")
	requireContains(t, got, intel.EcosystemNPM, "debug", "2.6.9")
}

// TestExpandPnpmLockV9 covers the schema-9 packages map.
func TestExpandPnpmLockV9(t *testing.T) {
	const lock = `lockfileVersion: '9.0'
packages:
  /lodash@4.17.21:
    resolution: {integrity: sha512-xxx}
  /@types/node@20.0.0:
    resolution: {integrity: sha512-yyy}
  /react@18.2.0(react-dom@18.2.0):
    resolution: {integrity: sha512-zzz}
`
	got := mustExpand(t, "pnpm-lock.yaml", packagemanager.ManifestKindPnpmLockYAML, lock)
	requireContains(t, got, intel.EcosystemNPM, "lodash", "4.17.21")
	requireContains(t, got, intel.EcosystemNPM, "@types/node", "20.0.0")
	// Peer-suffix is stripped.
	requireContains(t, got, intel.EcosystemNPM, "react", "18.2.0")
}

// TestExpandYarnLockV1 covers the original yarn classic format.
func TestExpandYarnLockV1(t *testing.T) {
	const lock = `# THIS IS AN AUTOGENERATED FILE.

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

"@types/node@^20.0.0":
  version "20.0.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.0.0.tgz"

"express@^4.18.2", "express@~4.18":
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"
`
	got := mustExpand(t, "yarn.lock", packagemanager.ManifestKindYarnLock, lock)
	requireContains(t, got, intel.EcosystemNPM, "lodash", "4.17.21")
	requireContains(t, got, intel.EcosystemNPM, "@types/node", "20.0.0")
	requireContains(t, got, intel.EcosystemNPM, "express", "4.18.2")
}

// TestExpandMissingFile_ReturnsNilNil: PMs emit lock refs speculatively,
// so missing files must not error.
func TestExpandMissingFile_ReturnsNilNil(t *testing.T) {
	exp := jslock.New()
	out, err := exp.Expand(packagemanager.ManifestRef{Path: "/nonexistent/lockfile", Kind: packagemanager.ManifestKindPackageLockJSON})
	require.NoError(t, err)
	require.Nil(t, out)
}

// TestExpandMalformedJSON_Errors: garbage input must fail-closed via
// error, not silently return empty (which would falsely look like
// "lockfile says no transitive deps").
func TestExpandMalformedJSON_Errors(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "package-lock.json")
	require.NoError(t, os.WriteFile(path, []byte("{not json"), 0o644))
	exp := jslock.New()
	_, err := exp.Expand(packagemanager.ManifestRef{Path: path, Kind: packagemanager.ManifestKindPackageLockJSON})
	require.Error(t, err)
	require.Contains(t, err.Error(), "parse package-lock.json")
}

func mustExpand(t *testing.T, name string, kind packagemanager.ManifestKind, contents string) []packagemanager.Install {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, name)
	require.NoError(t, os.WriteFile(path, []byte(contents), 0o644))
	out, err := jslock.New().Expand(packagemanager.ManifestRef{Path: path, Kind: kind})
	require.NoError(t, err)
	return out
}

func requireContains(t *testing.T, installs []packagemanager.Install, eco intel.Ecosystem, name, version string) {
	t.Helper()
	for _, ins := range installs {
		if ins.Ref.Ecosystem == eco && ins.Ref.Name == name && ins.Ref.Version == version {
			return
		}
	}
	t.Fatalf("expected install %s@%s (eco=%s) in:\n%v", name, version, eco, installs)
}

func requireMissing(t *testing.T, installs []packagemanager.Install, name string) {
	t.Helper()
	for _, ins := range installs {
		if ins.Ref.Name == name {
			t.Fatalf("did not expect install named %q in:\n%v", name, installs)
		}
	}
}
