// Command genpmlist emits the C header consumed by veto_interpose.c
// from the canonical Go slice in internal/packagemanager/pmlist.
// Invoked via `go generate ./internal/interposer/...` (see
// internal/interposer/generate.go) which the Makefile runs before
// compiling the dylib/so.
//
// Single source of truth: the Go slice (pmlist.InterposerPMs) is
// authoritative. Hand-editing pm_names.h would be silently overwritten
// by the next `go generate`; the file's header banner says so.
//
// Output shape (matches veto_interpose.c's expectations):
//
//	// Code generated by ... ; DO NOT EDIT.
//	#ifndef VETO_PM_NAMES_H
//	#define VETO_PM_NAMES_H
//	static const char *const PM_NAMES[] = {
//	  "npm", "npx", ...,
//	  NULL,
//	};
//	#endif
//
// Writes to the path passed as -o (default: stdout). The Makefile
// pipes stdout > internal/interposer/pm_names.h; the in-repo
// `go generate` directive uses -o so the generator is self-contained
// and can be run standalone without shell redirection.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/brynbellomy/veto/internal/packagemanager/pmlist"
)

func main() {
	out := flag.String("o", "", "output file path; empty = stdout")
	flag.Parse()

	var w io.Writer = os.Stdout
	if *out != "" {
		f, err := os.Create(*out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "genpmlist: create %s: %v\n", *out, err)
			os.Exit(1)
		}
		defer f.Close()
		w = f
	}

	if err := emit(w, pmlist.InterposerPMs); err != nil {
		fmt.Fprintf(os.Stderr, "genpmlist: write: %v\n", err)
		os.Exit(1)
	}
}

// emit writes the C header to w. Pulled out so a test can call it
// against a known input and assert the byte-exact output.
func emit(w io.Writer, names []string) error {
	var b strings.Builder
	b.WriteString("// Code generated by internal/interposer/cmd/genpmlist; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Single source of truth: internal/packagemanager/pmlist.InterposerPMs.\n")
	b.WriteString("// Regenerate via `go generate ./internal/interposer/...` or `make interposer`.\n")
	b.WriteString("\n")
	b.WriteString("#ifndef VETO_PM_NAMES_H\n")
	b.WriteString("#define VETO_PM_NAMES_H\n")
	b.WriteString("\n")
	b.WriteString("static const char *const PM_NAMES[] = {\n")
	for _, n := range names {
		// Names are ASCII-only PM binaries; no escaping needed. A
		// defensive sanity check guards against a future addition
		// that smuggles a quote/backslash in.
		if strings.ContainsAny(n, "\"\\\n\r\t") {
			return fmt.Errorf("PM name %q contains a character that would break C string literal escaping", n)
		}
		fmt.Fprintf(&b, "  %q,\n", n)
	}
	b.WriteString("  NULL,\n")
	b.WriteString("};\n")
	b.WriteString("\n")
	b.WriteString("#endif // VETO_PM_NAMES_H\n")
	_, err := io.WriteString(w, b.String())
	return err
}
